default: &default
  encoding: unicode
  adapter: postgresql
  pool: 5
  username: recipe_hunter
  password: dbpassword

development:
  <<: *default
  database: recipe_hunter_development

test:
  <<: *default
  database: recipe_hunter_test

production:
  <<: *default
  database: recipe_hunter_production

# Create Role before rake db:migrate
# CREATE ROLE recipe_hunter WITH CREATEDB LOGIN ENCRYPTED PASSWORD 'dbpassword';